version: '3'

services:
  web:
    build: .
    ports:
      - "5100:5100"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 